```{r}
eye_color <- c(2,2,4,1,5,5,5,6,1,3,6,3,1,4)
feye_color = factor(eye_color)
levels(feye_color) <- c("amber","blue","brown","gray","green","hazel")
```

```{r}
empathy_score <- c(15,21,45,32,61,74,53,92,83,22,67,55,42,44)
eyes_and_empathy  <- list(eyes_code=eye_color, eyes=feye_color, empathy=empathy_score)

code <- eyes_and_empathy[1]
code

```

```{r}
t.result <- t.test(eyes_and_empathy$empathy, mu = 30)
t.result$p.value

```

```{r}
e <- data.frame(eye_color, feye_color, empathy_score)
e[7,]
edit(e)
```

```{r}
e.blue <- e$empathy_score[e$feye_color=="blue"]
e.green <- e$empathy_score[e$feye_color=="green"]
e.hazel <- e$empathy_score[e$feye_color=="hazel"]

e.averages <- c(mean(e.blue), mean(e.green), mean(e.hazel))
e.amounts <- c(length(e.blue), length(e.green), length(e.hazel))
colors <- c("blue","green","hazel")
e.averages.frame <- data.frame(color=colors, average=e.averages, n=e.amounts)
e.averages.frame
```

```{r}
anorexia$Postwt - anorexia$Prewt
t.test(anorexia$Postwt - anorexia$Prewt, mu=0)
aov(Postwt-Prewt ~ Treat, data=anorexia)
```
